### ISSUE TITLE
organize_project needs to include usage report in output project

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando-util#17]
Changes in lando now save a resource usage file to  /bespin/output-data: https://github.com/Duke-GCB/lando/pull/169
This file should be included in the output project. 
Perhaps in `results/docs/logs`.

**Comment by dleehr** [comment]
In 
https://github.com/Duke-GCB/lando/pull/169 I chose to put the usage report in `Paths.OUTPUT_DATA`, assuming that it would be swept up, so that was a mistake. For the fix, I have two questions:

1. Is there a better directory for lando to write this to?
2. Should we not upload leftovers in `Paths.OUTPUT_DATA`?

**Comment by johnbradley** [comment]
> Is there a better directory for lando to write this to?

It seemed like a log file to me, but I'm open to other suggestions. I remember David wanting the top level directories to be clean as possible.

> Should we not upload leftovers in `Paths.OUTPUT_DATA`?

After all the issues we had with `.tmp*` directories showing up in our output project I guess I'm a little hesitant.

**Comment by johnbradley** [comment]
Another option would be to explicitly have a `scripts` and `logs` directories in `Paths.OUTPUT_DATA` along side `results`. Then we could just copy these directories to their final location in organize project.

**Comment by johnbradley** [comment]
Met with @dleehr.
Decided to fix this issue by moving the usage report into place.
Create issue #18 to look into simplifying the resulting project which would simplify specifying what is to be uploaded.
