### ISSUE TITLE
Upload Project: Record provenance data

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando-util#3]
There is existing functionality in lando that needs to be ported over to this repository:
https://github.com/Duke-GCB/lando/blob/master/lando/worker/provenance.py

**Comment by dleehr** [comment]
Good to keep this in the milestone, to ensure that all data created by bespin workflows have the basic provenance records that we've been providing under lando classic.

**Comment by johnbradley** [comment]
PR #14  mostly implemented this, but is expecting `input_file_version_ids ` to be passed in. 
https://github.com/Duke-GCB/lando-util/blob/31f562466facbbee7eb5cd112eff941638065ff2/lando_util/upload.py#L29

Unfortunately lando only has DukeDS file ids it received from bespin-api. 

NOTE: DukeDS provenance calls the field type `dds_file` but the value must be a `dds_file_version` id.

**Comment by johnbradley** [comment]
I was thinking that the `download` operation could optionally write a JSON file that lists all the FileVersionIds it downloaded from DukeDS. Then this file could be used when creating the activity.

**Comment by johnbradley** [comment]
Fixed by #16
