### ISSUE TITLE
Repo hygiene

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando-util#8]
In reviewing #7 I noticed there are still some things to do on this repo:

- [x] cleanup leftovers in setup.py
- [x] Configure for CI
- [x] Document development requirements
- [x] Add License

**Comment by johnbradley** [comment]
CI configured by #9 and I think the license was there from the beginning.

**Comment by dleehr** [comment]
> I think the license was there from the beginning.

You're right, it's in the [initial commit](6636df2ac6acf7299ac4ab2d8c97b685622f7726). I think I was looking for it in #1 and #7, so apologies for the confusion.
